project:
  type: website

website:
  title: "GEO511_FinalProject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    includes:
        after_body: include/after_body.html
