project:
  type: website
  output-dir: docs

website:
  title: "GEO511 Final Project - Mia Maines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    includes:
        after_body: include/after_body.html
